#!/bin/sh

# PROVIDE: dnstap
# REQUIRE: NETWORKING ldconfig syslogd
# BEFORE: named

. /etc/rc.subr

export PATH=/usr/local/bin:$PATH
name="dnstap"
pidfile="/var/run/dnstap.pid"
command="/usr/sbin/daemon"
command_args="-c -r -t $name -S -T $name -P $pidfile /home/drew/dnstap/bin/dnstap"
start_postcmd=dnstap_poststart

dnstap_poststart()
{
    echo "waiting for dnstap to start"
    i=0
    while ! /home/drew/dnstap/bin/dnstap_test; do
    	echo "waiting for dnstap to start"
        sleep 1
        i=`echo $i+1|bc`
        if [ $i -ge 10 ]; then
            echo "Server did not appear to start"
            exit 1
        fi
    done
}

load_rc_config $name
run_rc_command "$1"
