#!/bin/sh

# PROVIDE: dnstap
# REQUIRE: NETWORKING ldconfig syslogd
# BEFORE: named

. /etc/rc.subr

load_rc_config $name

fail() { echo $@>&2; exit 1; }

test -n "$dnstap_home" || fail "dnstap_home not defined"

name="dnstap"
pidfile="/var/run/dnstap.pid"
command="/usr/sbin/daemon"
command_args="-c -r -t $name -S -T $name -P $pidfile $dnstap_home/bin/dnstap"
start_postcmd=dnstap_poststart

dnstap_poststart()
{
    ps ax > /foo
    echo "waiting for dnstap to start"
    i=0
    while ! $dnstap_home/bin/dnstap_test; do
    	echo "waiting for dnstap to start"
        sleep 1
        i=`echo $i+1|bc`
        if [ $i -ge 10 ]; then
            echo "Server did not appear to start"
            exit 1
        fi
    done
    sleep 5
    echo "ready"
}

export PATH=/usr/local/bin:$PATH

run_rc_command "$1"
