#!/bin/sh

# PROVIDE: dnstap
# REQUIRE: NETWORKING ldconfig syslogd
# BEFORE: named

. /etc/rc.subr

name="dnstap"
rcvar="${name}_enabled"
start_cmd="${name}_start"

command="/home/drew/bindrev/bin/dnstap"
pidfile="/var/run/dnstap.pid"

dnstap_start()
{
    echo "Starting dnstap"
    export PATH=/usr/local/bin:$PATH
    /usr/sbin/daemon -S -T dnstap -c -t dnstap -P $pidfile $command
    i=0
    while ! /home/drew/bindrev/bin/bindrev_client test; do
        echo "Waiting for server start"
        sleep 1
        i=`echo $i+1|bc`
        if [ $i -ge 10 ]; then
            echo "Server did not appear to start"
            exit 1
        fi
    done
}

load_rc_config $name
run_rc_command "$1"
